//登录
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

//注销
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

//刷新用户数据
export const REFRESH_USER_REQUEST = 'REFRESH_USER_REQUEST'
export const REFRESH_USER_FAILURE = 'REFRESH_USER_FAILURE'
export const REFRESH_USER_SUCCESS = 'REFRESH_USER_SUCCESS'

//注册
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

